import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/app/(pages)/_components/providers";
import Navbar from "@/app/(pages)/_components/navbar";
import SidebarLeft from "./_components/sidebar-left";
import SidebarRight from "./_components/sidebar-right";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Providers>
					<Navbar />
					<div className="flex w-full items-center justify-center p-2 gap-2">
						<SidebarLeft />
						{children}
						<SidebarRight />
					</div>
				</Providers>
			</body>
		</html>
	);
}
