version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  node: circleci/node@5.1.0

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup:
          configure_default_region: false
          configure_profile_region: true
          disable_aws_pager: true
          override_installed: false
          aws_access_key_id: ${secrets.AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${secrets.AWS_ACCESS_KEY_ID}
          region: ${secrets.AWS_REGION}
      - node/install
      - run:
          command: npm run sst deploy --stage prod --region ${secrets.AWS_REGION}

workflows:
  deploy:
    jobs:
      - deploy:
          context: valbuddy
