version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.0

jobs:
  deploy:
    executor: ubuntu-latest
    context: valbuddy

    steps:
      - checkout

      - aws-cli/setup:
          region: ${{ context.valbuddy.AWS_REGION }}
          access-key-id: ${{ context.valbuddy.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ context.valbuddy.AWS_SECRET_ACCESS_KEY }}

      - run: npx sst deploy --stage prod --region ${{ context.valbuddy.AWS_REGION }}
