version: 2.1
setup: true
orbs:
  dynamic: bjd2385/dynamic-continuation@3.7.1
workflows:
  on-commit:
    jobs:
      - dynamic/continue:
          context: circleci
          modules: |
            /backend
            /frontend
          filters:
            branches:
              only: master
