version: 2.1

orbs:
    aws-cli: circleci/aws-cli@4.1.1
    node: circleci/node@5.1.0
    go: circleci/go@1.8.0
jobs:
    deploy-frontend:
        working_directory: ~/app/frontend
        docker:
            - image: cimg/base:current
        resource_class: arm.large
        steps:
            - setup_remote_docker:
                  version: default
            - checkout:
                  path: ~/app
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "package-lock.json" }}
                      - dependency-cache-
            - aws-cli/setup:
                  configure_default_region: false
                  configure_profile_region: false
                  disable_aws_pager: true
                  override_installed: false
                  aws_access_key_id: ${AWS_ACCESS_KEY_ID}
                  aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
                  region: ${AWS_REGION}
            - node/install
            - run:
                  command: npm install
                  name: Install packages
            - run:
                  command: npx sst deploy --stage prod --region ${AWS_REGION}
                  name: Go to Frontend Folder/Run SST Deploy CMD
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
    deploy-backend:
        working_directory: ~/app/backend
        docker:
            - image: cimg/base:current
        resource_class: arm.large
        steps:
            - setup_remote_docker:
                  version: default
            - checkout:
                  path: ~/app
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "package-lock.json" }}
                      - dependency-cache-
            - aws-cli/setup:
                  configure_default_region: false
                  configure_profile_region: false
                  disable_aws_pager: true
                  override_installed: false
                  aws_access_key_id: ${AWS_ACCESS_KEY_ID}
                  aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
                  region: ${AWS_REGION}
            - node/install
            - go/install
            - run:
                  command: mkdir -p ~/app/backend/zip/
                  name: Make zip folder
            - run:
                  command: go build -o zip/bootstrap cmd/main.go
                  name: Build Binary
            - run:
                  command: npm install
                  name: Install packages
            - run:
                  name: Set HOME environment variable
                  command: echo 'export HOME_PATH=$HOME' >> $BASH_ENV

            - run:
                  command: cdk deploy --require-approval never
                  name: Deploy using CDK
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules

workflows:
    run-deploy-frontend:
        jobs:
            - deploy-frontend:
                  context:
                      - valbuddy
    run-deploy-backend:
        jobs:
            - deploy-backend:
                  context:
                      - valbuddy
