version: 2.1

orbs:
    aws-cli: circleci/aws-cli@4.1.1
    node: circleci/node@5.1.0

jobs:
    deploy-frontend:
        working_directory: ~/frontend
        docker:
            - image: cimg/base:current
        resource_class: arm.large
        steps:
            - setup_remote_docker:
                  version: default
            - checkout:
                  path: ~/frontend
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "package-lock.json" }}
                      - dependency-cache-
            - aws-cli/setup:
                  configure_default_region: false
                  configure_profile_region: false
                  disable_aws_pager: true
                  override_installed: false
                  aws_access_key_id: ${AWS_ACCESS_KEY_ID}
                  aws_secret_access_key: ${AWS_ACCESS_KEY_ID}
                  region: ${AWS_REGION}
            - node/install
            - run:
                  name: Verify package-lock.json
                  command: ls ~/backend/package-lock.json
            - run:
                  command: npm ci --prefix ~/frontend
                  name: Install packages
            - run:
                  command: npx sst deploy --stage prod --region ${AWS_REGION} --prefix ~/frontend
                  name: Go to Frontend Folder/Run SST Deploy CMD
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
    deploy-backend:
        working_directory: ~/backend
        docker:
            - image: cimg/base:current
        resource_class: arm.large
        steps:
            - setup_remote_docker:
                  version: default
            - checkout:
                  path: ~/backend
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "package-lock.json" }}
                      - dependency-cache-
            - aws-cli/setup:
                  configure_default_region: false
                  configure_profile_region: false
                  disable_aws_pager: true
                  override_installed: false
                  aws_access_key_id: ${AWS_ACCESS_KEY_ID}
                  aws_secret_access_key: ${AWS_ACCESS_KEY_ID}
                  region: ${AWS_REGION}
            - node/install
            - run:
                  name: Verify package-lock.json
                  command: ls ~/backend/package-lock.json
            - run:
                  command: npm ci --prefix ~/backend
                  name: Install packages
            - run:
                  command: npx sst deploy --stage prod --region ${AWS_REGION} --prefix ~/backend
                  name: Run SST Deploy CMD
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules

workflows:
    run-deploy-frontend:
        jobs:
            - deploy-frontend:
                  context:
                      - valbuddy
    run-deploy-backend:
        jobs:
            - deploy-backend:
                  context:
                      - valbuddy
