version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  node: circleci/node@5.1.0

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - aws-cli/setup:
          configure_default_region: false
          configure_profile_region: false
          disable_aws_pager: true
          override_installed: false
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_ACCESS_KEY_ID}
          region: ${AWS_REGION}
      - node/install
      - run:
          command: npm ci
          name: Install NPM packages
      - run:
          command: npx sst deploy --stage prod --region ${AWS_REGION}
          name: Run SST Deploy CMD
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./.next/cache

workflows:
  run-deploy:
    jobs:
      - deploy:
          context: valbuddy
