version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup:
          configure_default_region: false
          configure_profile_region: true
          disable_aws_pager: true
          override_installed: false
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_ACCESS_KEY_ID}
          region: ${AWS_REGION}
      - node/install
      - run:
          command: npm ci
          name: Install NPM packages
      - docker/install-docker
      - run:
          command: sudo dockerd
          name: Run Docker Daemon
      - run:
          command: npx sst deploy --stage prod --region ${AWS_REGION}
          name: Run SST Deploy CMD

workflows:
  run-deploy:
    jobs:
      - deploy:
          context: valbuddy
